# Generated by Django 4.0.5 on 2022-12-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_users_remove_profile_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matricula',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Matricula'),
        ),
    ]
